apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.server.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-db
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
