apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          ports:
            - containerPort: {{ .Values.kafkaUi.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "{{ .Values.kafkaUi.clusterName }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: |
                {{- $replicas := int .Values.replicaCount }}
                {{- range $i := until $replicas }}
                kafka-{{ $i }}.kafka:{{ $.Values.kafka.port }}{{ if not (eq (add $i 1) $replicas) }},{{ end }}
                {{- end }}