namespace: kallepallirupesh-dev
ocProject: rm2.thpm.p1

route:
  enabled: true

ingress:
  enabled: false
  className: nginx

replicaCount: 1

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 11434

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "16Gi"
    cpu: "8"

persistence:
  enabled: true
  size: 50Gi
  mountPath: /tmp/.ollama

env:
  OLLAMA_NUM_PARALLEL: "5"
  OLLAMA_MAX_LOADED_MODELS: "5"
  OLLAMA_KEEP_ALIVE: "24h"

model:
  - llama3.3:70b
  - bge-m3
  - mxbai-embed-large
