apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5678
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "{{ .Values.auth.user }}"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "{{ .Values.auth.password }}"
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: N8N_PORT
              value: "5678"
            - name: NODE_ENV
              value: "production"
            - name: N8N_USER_FOLDER
              value: "/tmp/.n8n"
          volumeMounts:
            - name: data
              mountPath: /tmp/.n8n
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: n8n-pvc
