apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: browser-proxy
  template:
    metadata:
      labels:
        app: browser-proxy
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "nginx", "-g", "daemon off;" ]
          ports:
            - containerPort: 9222
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9222
            initialDelaySeconds: 2
            periodSeconds: 4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9222
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: conf
          configMap:
            name: nginx-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
