apiVersion: v1
kind: Service
metadata:
  name: browser-proxy
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9222
  selector:
    app: browser-proxy
