apiVersion: v1
kind: Service
metadata:
  name: {{ include "browser-service.fullname" . }}
  labels:
    {{- include "browser-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.proxy.port }}
      targetPort: {{ .Values.proxy.targetPort }}
      protocol: TCP
      name: proxy
  selector:
    {{- include "browser-service.selectorLabels" . | nindent 4 }}
