{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Chart.Name }}-{{ .Values.namespace }}.apps.{{ .Values.ocProject }}.openshiftapps.com
  to:
    kind: Service
    name: {{ .Chart.Name }}
  port:
    targetPort: http
  tls:
    termination: edge
  {{- end }}
