apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "browser-service-registry.fullname" . }}
  labels:
    {{- include "browser-service-registry.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "browser-service-registry.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge