image:
  repository: n8nio/n8n
  tag: latest

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

auth:
  user: admin
  password: admin123

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

service:
  port: 5678

route:
  enabled: true
  host: ""
