---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: browser-service
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jdk17-chrome:latest
  output:
    to:
      kind: ImageStreamTag
      name: browser-service:latest