apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-slim
spec:
  tags:
    - name: latest
      annotations:
        description: "OpenJDK 17 slim base image from Docker Hub"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/openjdk-17:1.17-1
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-chrome
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: browser-service
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: jdk17-chrome
spec:
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/openjdk-17:1.17-1

      USER 0

      # Install dependencies
      RUN microdnf install -y \
            unzip curl atk gtk3 libX11 libXcomposite libXcursor libXdamage libXext libXfixes \
            libXi libXrandr libXrender nss nspr alsa-lib cups-libs libdrm mesa-libgbm pango glib2 \
            xorg-x11-fonts-Type1 xorg-x11-fonts-misc \
            && microdnf clean all

      # Download Chrome-for-Testing
      RUN curl -L https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chrome-linux64.zip \
          -o /tmp/chrome.zip \
          && unzip /tmp/chrome.zip -d /opt/chrome \
          && rm -f /tmp/chrome.zip

      # Permissions for OpenShift non-root UID
      RUN chmod -R 755 /opt/chrome \
          && mkdir -p /app /tmp/chrome /home/chromeuser \
          && chmod -R g+rwX /app /tmp /home/chromeuser \
          && chown -R 1000:0 /opt/chrome /app /tmp /home/chromeuser

      # Add chrome to PATH
      ENV PATH="/opt/chrome/chrome-linux64:${PATH}"
      ENV HOME=/home/chromeuser
      ENV TMPDIR=/tmp
      ENV CHROME_USER_DATA_DIR=/tmp/chrome

      WORKDIR /app

      USER 1000

      CMD ["bash"]
strategy:
  type: Docker
output:
  to:
    kind: ImageStreamTag
    name: jdk17-chrome:latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-service-nginx-conf
data:
  nginx.conf: |
    error_log /dev/stderr info;
    pid /tmp/nginx.pid;

    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {

        # ---------------------------------------
        # WebSocket upgrade handling
        # ---------------------------------------
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }

        server {
            listen 9223;

            # ---------------------------------------
            # Health check
            # ---------------------------------------
            location = /healthz {
                return 200 'ok';
                add_header Content-Type text/plain;
            }

            # =====================================================
            # CDP PROXY (PORT ONLY)
            #
            # URL FORMAT:
            #   /proxy/<port>/...
            #
            # EXAMPLES:
            #   /proxy/41273/json
            #   /proxy/41273/devtools/page/XXXX
            #
            # =====================================================
            location ~ ^/proxy/([0-9]+)(/.*)$ {

                set $target_port $1;
                set $forward_path $2;

                # ---------------------------------------
                # SAFETY GUARD
                # Allow only a safe port range (recommended)
                # ---------------------------------------
                if ($target_port !~ ^4[0-9]{4}$) {
                    return 403;
                }

                # ---------------------------------------
                # Proxy to local Chrome instance
                # ---------------------------------------
                proxy_pass http://127.0.0.1:$target_port$forward_path;

                proxy_http_version 1.1;

                # 🔑 Chrome requires this Host header
                proxy_set_header Host 127.0.0.1;

                # WebSocket headers
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";

                # Forwarding headers
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # REQUIRED for CDP
                proxy_buffering off;
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
        }
    }

---
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: browser-service
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jdk17-chrome:latest
  output:
    to:
      kind: ImageStreamTag
      name: browser-service:latest