apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-slim
spec:
  tags:
    - name: latest
      annotations:
        description: "OpenJDK 17 slim base image from Docker Hub"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/openjdk-17:1.17-1
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-chrome
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: jdk17-chrome
spec:
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/openjdk-17:1.17-1

      USER root

      # Install unzip & curl
      RUN microdnf install -y unzip curl && microdnf clean all

      # Download Chrome-for-Testing v143
      RUN curl -L https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chrome-linux64.zip -o chrome-linux64.zip \
          && unzip chrome-linux64.zip -d /opt/chrome \
          && rm chrome-linux64.zip

      ENV PATH="/opt/chrome/chrome-linux64:${PATH}"

      WORKDIR /app
      CMD ["bash"]

  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: jdk17-chrome:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: springboot-b2i
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: no-code-ai-automation
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: springboot-b2i
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jdk17-slim:latest
  output:
    to:
      kind: ImageStreamTag
      name: springboot-b2i:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
