apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-slim
spec:
  tags:
    - name: latest
      annotations:
        description: "OpenJDK 17 slim base image from Docker Hub"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/openjdk-17:1.17-1
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jdk17-chrome
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: browser-service
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: browser-service-registry
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: test-runner-slave
---
