server:
  port: 8080
spring:
  application:
    name: ai-test-planner
  kafka:
    bootstrap-servers: >-
      172.19.226.122:9092
  ai:
    openai:
      api-key: ${OPEN_ROUTER_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: meta-llama/llama-3.2-3b-instruct:free
          temperature: 0
          top-p: 0.1
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: tinyllama
#        options:
#          temperature: 0
#          top-p: 0.1
#          max-tokens: 5000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,liveness   # expose actuator endpoints
  metrics:
    export:
      prometheus:
        enabled: true                     # enable Prometheus registry
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
