server:
  port: 8080
spring:
  application:
    name: ai-test-planner
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  kafka:
    bootstrap-servers: >-
      172.19.226.122:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/testai
    username: testai
    password: testai
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.3:70b
          temperature: 0
          top-p: 0.1
          # max-tokens: 5000
      embedding:
        options:
          model: bge-m3
    #    openai:
    #      api-key: ${OPEN_ROUTER_KEY}
    #      base-url: https://openrouter.ai/api
    #      chat:
    #        options:
    #          model: openrouter/free
    #          temperature: 0
    #          top-p: 0.1
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,liveness # expose actuator endpoints
  metrics:
    export:
      prometheus:
        enabled: true # enable Prometheus registry
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    com.vr.ai.test.planner: debug
    org.springframework.ai: DEBUG