server:
  port: 8080
spring:
  application:
    name: ai-test-planner
  #  data:
  #    redis:
  #      host: redis
  #      port: 6379
  #      password: StrongPassword123!
  ai:
    ollama:
      base-url: https://ollama-kallepallirupesh-dev.apps.rm2.thpm.p1.openshiftapps.com
      chat:
        model: qwen2.5:0.5b
        options:
          temperature: 0
          top-p: 0.1
          max-tokens: 2000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,liveness   # expose actuator endpoints
  metrics:
    export:
      prometheus:
        enabled: true                     # enable Prometheus registry
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
