server:
  port: 8080
spring:
  application:
    name: ai-test-planner
  kafka:
    bootstrap-servers: >-
      kafka-0-ext:9092,
      kafka-1-ext:9092,
      kafka-2-ext:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: tinyllama
        options:
          temperature: 0
          top-p: 0.1
          max-tokens: 4000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,liveness   # expose actuator endpoints
  metrics:
    export:
      prometheus:
        enabled: true                     # enable Prometheus registry
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
